Week11Day5/Models/ErrorViewModel.cs
using System;

namespace Week11Day4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Week11Day5/Models/FullWeatherForecast.cs
namespace Week11Day5.Models
{
    public class FullWeatherForecast
    {
        public string RainForecast { get; set; }
        public double Humidity { get; set; }
    }
}

Week11Day5/Models/Student.cs
namespace Week11Day5.Models
{
    public class Student
    {
        public int RollNo { get; set; }
        public string Name { get; set; }
    }
}

Week11Day5/Controllers/BankInfoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Week11Day4.Services;
using WorldlineLiveServiceReference;

namespace Week11Day4.Controllers
{
    public class BankInfoController : Controller
    {
        private readonly IBankInfoService _bankInfoService;

        public BankInfoController(IBankInfoService bankInfoService)
        {
            _bankInfoService = bankInfoService;
        }

        // GET: BankInfoController
        public async Task<ActionResult> IndexAsync()
        {
            var bankDetails = await _bankInfoService.GetByIfscAsync("ICIC0000011");

            return View(bankDetails);
        }
    }
}

Week11Day5/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Week11Day4.Models;

namespace Week11Day4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Week11Day5/Controllers/StudentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Week11Day5.Models;
using Week11Day5.Services;

namespace Week11Day5.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;

        public StudentController(IStudentService studentService)
        {
            _studentService = studentService;
        }

        // GET: StudentController
        public ActionResult Index()
        {
            var students = _studentService.GetAllStudents();

            return View(students);
        }

        [HttpPost]
        public ActionResult GetByName(string studentName)
        {
            List<Student> students;

            if (!string.IsNullOrEmpty(studentName))
                students = _studentService.GetStudentsByName(studentName);
            else
                students = _studentService.GetAllStudents();
            
            //return View("Index", students);
            return View(nameof(Index), students);
        }
    }
}

Week11Day5/Controllers/WeatherForecastController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Week11Day5.Services;

namespace Week11Day5.Controllers
{
    public class WeatherForecastController : Controller
    {
        private readonly IWeatherForecastService _weatherForecastService;

        public WeatherForecastController(IWeatherForecastService weatherForecastService)
        {
            _weatherForecastService = weatherForecastService;
        }

        // GET: WeatherForcastController
        public async Task<ActionResult> IndexAsync()
        {
            var fullForecast = await _weatherForecastService.GetFullForecastAsync("mumbai");
            return View(fullForecast);
        }
    }
}

Week11Day5/Views/BankInfo/Index.cshtml
@model IEnumerable<WorldlineLiveServiceReference.BankDetails>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Bank)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ifsc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MicrCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Branch)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StdCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.District)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>@item.Bank</td>
            <td>@item.Ifsc</td>
            <td>@item.MicrCode</td>
            <td>@item.Branch</td>
            <td>@item.StdCode</td>
            <td>@item.Contact</td>
            <td>@item.City</td>
            <td>@item.District</td>
            <td>@item.State</td>
        </tr>
}
    </tbody>
</table>

Week11Day5/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Week11Day5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Week11Day4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Week11Day4</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BankInfo" asp-action="Index">BankInfo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WeatherForecast" asp-action="Index">WeatherForecast</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Week11Day4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Week11Day5/Views/Student/Index.cshtml
@model IEnumerable<Week11Day5.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h1>Student List</h1>

<div class="row">
    <div class="col-md-12">
        <form asp-action="GetByName">
            <div class="row form-group">
                <div class="col-md-4">
                    <label class="control-label">Search By Student</label>
                    <input type="text" name="studentName" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Show Students" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RollNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.RollNo</td>
                <td>@item.Name</td>
            </tr>
        }
    </tbody>
</table>

Week11Day5/Views/WeatherForecast/Index.cshtml
@using Week11Day5.Models
@model FullWeatherForecast

@{
    ViewData["Title"] = "Index";
}

<h1>Weather forecast by Worldline International</h1>
<p>
    Dear employees, this is the weather forecast for today.

    @Model.RainForecast

    @if (@Model.Humidity > 50)
    {
        <div>There is too much humidity today of @Model.Humidity</div>
    }
    else
    {
        <div>There is less humidity today of @Model.Humidity. So we can work 2 hours extra in office</div>           
    }
</p>